import "server-only";

/**
 * Minimal Meta Graph API client for fetching Lead Ads form submissions.
 *
 * Auth: a long-lived Page Access Token with `leads_retrieval` permission.
 * Generated by the page admin via Graph API Explorer (no Meta App review
 * needed because they're the admin themselves).
 *
 * Token lifecycle: ~60 days when issued from a long-lived user token.
 * The admin page surfaces the expiry; admin re-generates and updates env
 * before it expires.
 */

const GRAPH_BASE = "https://graph.facebook.com/v23.0";

export interface MetaLeadForm {
  id: string;
  name: string;
  status?: string;
  page_id?: string;
}

export interface MetaLeadRaw {
  id: string;
  created_time: string;
  ad_id?: string;
  ad_name?: string;
  adset_id?: string;
  adset_name?: string;
  campaign_id?: string;
  campaign_name?: string;
  form_id?: string;
  is_organic?: boolean;
  platform?: string;
  field_data: Array<{ name: string; values: string[] }>;
}

function checkToken() {
  const token = process.env.META_PAGE_ACCESS_TOKEN;
  const pageId = process.env.META_PAGE_ID;
  if (!token) throw new Error("META_PAGE_ACCESS_TOKEN not configured");
  if (!pageId) throw new Error("META_PAGE_ID not configured");
  return { token, pageId };
}

async function graphFetch<T>(path: string, params: Record<string, string> = {}): Promise<T> {
  const { token } = checkToken();
  const search = new URLSearchParams({ access_token: token, ...params });
  const url = `${GRAPH_BASE}${path}?${search.toString()}`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Graph API ${res.status}: ${text.slice(0, 240)}`);
  }
  return (await res.json()) as T;
}

interface PagedResponse<T> {
  data: T[];
  paging?: { cursors?: { before?: string; after?: string }; next?: string };
}

export async function listLeadForms(): Promise<MetaLeadForm[]> {
  const { pageId } = checkToken();
  const forms: MetaLeadForm[] = [];
  let after: string | undefined;
  for (let page = 0; page < 20; page++) {
    const params: Record<string, string> = {
      fields: "id,name,status,page",
      limit: "50",
    };
    if (after) params.after = after;
    const res = await graphFetch<PagedResponse<MetaLeadForm & { page?: { id: string } }>>(
      `/${pageId}/leadgen_forms`,
      params
    );
    for (const f of res.data) {
      forms.push({ id: f.id, name: f.name, status: f.status, page_id: f.page?.id });
    }
    after = res.paging?.cursors?.after;
    if (!res.paging?.next || !after) break;
  }
  return forms;
}

export async function listFormLeads(
  formId: string,
  sinceUnix?: number
): Promise<MetaLeadRaw[]> {
  const leads: MetaLeadRaw[] = [];
  let after: string | undefined;
  for (let page = 0; page < 50; page++) {
    const params: Record<string, string> = {
      fields:
        "id,created_time,ad_id,ad_name,adset_id,adset_name,campaign_id,campaign_name,form_id,is_organic,platform,field_data",
      limit: "100",
    };
    if (after) params.after = after;
    if (sinceUnix) params.filtering = JSON.stringify([{ field: "time_created", operator: "GREATER_THAN", value: sinceUnix }]);
    const res = await graphFetch<PagedResponse<MetaLeadRaw>>(`/${formId}/leads`, params);
    leads.push(...res.data);
    after = res.paging?.cursors?.after;
    if (!res.paging?.next || !after) break;
  }
  return leads;
}

/** Extract canonical fields from Meta's field_data array. */
export function extractFieldData(raw: MetaLeadRaw): {
  full_name: string | null;
  email: string | null;
  phone: string | null;
  field_data_object: Record<string, string>;
} {
  const obj: Record<string, string> = {};
  for (const f of raw.field_data ?? []) {
    obj[f.name] = (f.values ?? []).join(", ");
  }
  const findKey = (...candidates: string[]) => {
    for (const c of candidates) {
      for (const [k, v] of Object.entries(obj)) {
        if (k.toLowerCase().includes(c.toLowerCase()) && v?.trim()) return v.trim();
      }
    }
    return null;
  };
  return {
    full_name: findKey("full_name", "name", "име"),
    email: findKey("email", "имейл"),
    phone: findKey("phone_number", "phone", "телефон"),
    field_data_object: obj,
  };
}

/** Verify a token can read the page's lead forms. Returns the page name on success. */
export async function verifyToken(): Promise<{ ok: boolean; pageName?: string; error?: string }> {
  try {
    const { pageId } = checkToken();
    const res = await graphFetch<{ name: string; id: string }>(`/${pageId}`, { fields: "id,name" });
    return { ok: true, pageName: res.name };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
